/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador_view.dialog;

import controlador_view.ControladorMain;
import controlador_view.VC;
import controlador_view.VCLocadores;
import javax.swing.JButton;
import modelo.Admin;

/**
 *
 * @author aluno2
 */
public class VCAgendamentoAdmin extends VC {
    private static Admin contexto;
    private static VCLocadores controlador;
    private static ControladorMain m;
    private int idUsuario;
    private int id_espaco;
    /**
     * Creates new form VCAgendamento
     * @param contexto
     * @param controlador
     * @param m
     */
    public VCAgendamentoAdmin(Admin contexto, VCLocadores controlador, ControladorMain m) {
        VCAgendamentoAdmin.contexto       = contexto;
        VCAgendamentoAdmin.controlador    = controlador;
        VCAgendamentoAdmin.m              = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        button_aceitar = new javax.swing.JButton();
        button_recusar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        text_tipo = new javax.swing.JLabel();
        text_endereco = new javax.swing.JLabel();
        text_lugares = new javax.swing.JLabel();
        text_diaria = new javax.swing.JLabel();
        text_status = new javax.swing.JLabel();
        text_usuario = new javax.swing.JLabel();
        button_ok = new javax.swing.JButton();
        button_checkout = new javax.swing.JButton();
        button_checkin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        text_dias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Tipo");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Endereco");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Lugares");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Diária");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Status");

        button_aceitar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        button_aceitar.setText("Aceitar");
        button_aceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_aceitarActionPerformed(evt);
            }
        });

        button_recusar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        button_recusar.setText("Recusar");
        button_recusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_recusarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Usuário que pediu");

        text_tipo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        text_tipo.setText("jLabel7");

        text_endereco.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        text_endereco.setText("jLabel8");

        text_lugares.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        text_lugares.setText("jLabel9");

        text_diaria.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        text_diaria.setText("jLabel10");

        text_status.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        text_status.setText("jLabel11");

        text_usuario.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        text_usuario.setText("jLabel12");

        button_ok.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        button_ok.setText("Ok");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        button_checkout.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        button_checkout.setText("checkout");

        button_checkin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        button_checkin.setText("checkin");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Quantidade de dias");

        text_dias.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        text_dias.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(button_checkin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_checkout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_aceitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_recusar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_dias))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_usuario)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_lugares)
                                            .addComponent(text_endereco)
                                            .addComponent(text_tipo)
                                            .addComponent(text_status)
                                            .addComponent(text_diaria))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_endereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_lugares))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_diaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_dias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_aceitar)
                    .addComponent(button_recusar)
                    .addComponent(button_ok)
                    .addComponent(button_checkout)
                    .addComponent(button_checkin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_aceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_aceitarActionPerformed
        // TODO add your handling code here:
        // fecha essa tela e deixa a do conrolador
        m.carregando(controlador, "");
        dispose();
        contexto.aceitarReserva(controlador, id_espaco, idUsuario);
    }//GEN-LAST:event_button_aceitarActionPerformed

    private void button_recusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_recusarActionPerformed
        // TODO add your handling code here:
        m.carregando(controlador, "");
        dispose();
        contexto.recusarReserva(controlador, id_espaco);
    }//GEN-LAST:event_button_recusarActionPerformed

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        // TODO add your handling code here:
        dispose();
        controlador.setVisible(true);
        controlador.setEnabled(true);
    }//GEN-LAST:event_button_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCAgendamentoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCAgendamentoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCAgendamentoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCAgendamentoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VCAgendamentoAdmin(contexto, controlador, m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_aceitar;
    private javax.swing.JButton button_checkin;
    private javax.swing.JButton button_checkout;
    private javax.swing.JButton button_ok;
    private javax.swing.JButton button_recusar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text_diaria;
    private javax.swing.JLabel text_dias;
    private javax.swing.JLabel text_endereco;
    private javax.swing.JLabel text_lugares;
    private javax.swing.JLabel text_status;
    private javax.swing.JLabel text_tipo;
    private javax.swing.JLabel text_usuario;
    // End of variables declaration//GEN-END:variables

    public void setText_diaria(String text_diaria) {
        this.text_diaria.setText(text_diaria);
    }

    public void setText_endereco(String text_endereco) {
        this.text_endereco.setText(text_endereco);
    }

    public void setText_lugares(String text_lugares) {
        this.text_lugares.setText(text_lugares);
    }

    public void setText_status(String text_status) {
        this.text_status.setText(text_status);
    }

    public void setText_tipo(String text_tipo) {
        this.text_tipo.setText(text_tipo);
    }

    public void setText_usuario(String text_usuario) {
        this.text_usuario.setText(text_usuario);
    }

    public void setIdUsuario(int idUsuario){
        this.idUsuario = idUsuario;
    }
    
    public void setId_espaco(int id_espaco){
        this.id_espaco = id_espaco;
    }

    public void setText_dias(String dias){
        text_dias.setText(dias);
    }
    public JButton getButton_checkin() {
        return button_checkin;
    }

    public JButton getButton_checkout() {
        return button_checkout;
    }
    
    
}
