/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador_view.dialog;

import controlador_view.ControladorMain;
import controlador_view.VC;
import controlador_view.VCLocadores;
import modelo.Locador;

/**
 *
 * @author Joel
 */

// é criada para mostrar opções aos espacos listados em "seus espacos
public class VCEspacoLocador extends VC {
    private static Locador contexto;
    private static VCLocadores controlador;
    private int idEspaco;
    private static ControladorMain m;
    /**
     * Creates new form VCEspacoInfo
     * @param contexto
     * @param controlador
     * @param m
     */
    public VCEspacoLocador(Locador contexto, VCLocadores controlador, ControladorMain m) {
        VCEspacoLocador.contexto       = contexto;
        VCEspacoLocador.controlador    = controlador;
        VCEspacoLocador.m              = m;
        setLocationRelativeTo(null);
        controlador.setEnabled(false);
        initComponents();
        
        m.viewDefault(controlador, this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        text_tipo = new javax.swing.JLabel();
        text_endereco = new javax.swing.JLabel();
        text_diaria = new javax.swing.JLabel();
        text_lugares = new javax.swing.JLabel();
        text_status_e = new javax.swing.JLabel();
        button_ok = new javax.swing.JButton();
        button_editar = new javax.swing.JButton();
        button_excluir = new javax.swing.JButton();
        edit_tipo = new javax.swing.JTextField();
        edit_endereco = new javax.swing.JTextField();
        edit_diaria = new javax.swing.JTextField();
        edit_lugares = new javax.swing.JTextField();
        edit_lugares_ocupados = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        text_comissao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Espaco");

        text_tipo.setText("Tipo");

        text_endereco.setText("Endereco");

        text_diaria.setText("Diária");

        text_lugares.setText("Lugares");

        text_status_e.setText("Ocupados");

        button_ok.setText("Ok");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        button_editar.setText("Atualizar");
        button_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editarActionPerformed(evt);
            }
        });

        button_excluir.setText("Excluir");
        button_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_excluirActionPerformed(evt);
            }
        });

        edit_lugares_ocupados.setEditable(false);

        jLabel1.setText("A arrecadar:  R$");

        text_comissao.setText("jLabel2");

        jLabel2.setText("por enquanto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_editar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(text_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_diaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edit_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(edit_tipo)
                            .addComponent(edit_diaria)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_lugares)
                            .addComponent(text_status_e))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edit_lugares_ocupados, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(edit_lugares)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_comissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tipo)
                    .addComponent(edit_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_endereco)
                    .addComponent(edit_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_diaria)
                    .addComponent(edit_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_lugares)
                    .addComponent(edit_lugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_lugares_ocupados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_status_e))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_comissao)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_ok)
                    .addComponent(button_editar)
                    .addComponent(button_excluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        // TODO add your handling code here:
        controlador.setVisible(true);
        controlador.setEnabled(true);
        
        dispose();
    }//GEN-LAST:event_button_okActionPerformed

    private void button_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_excluirActionPerformed
        // TODO add your handling code here:
        m.carregando(this, "");
        dispose();
        contexto.removerEspaco(controlador, idEspaco);
    }//GEN-LAST:event_button_excluirActionPerformed

    private void button_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editarActionPerformed
        // TODO add your handling code here:
        m.carregando(this, "");
        dispose();
        contexto.atualizarEspaco(controlador, idEspaco, edit_diaria.getText(), edit_tipo.getText(), edit_lugares.getText(), edit_endereco.getText());
    }//GEN-LAST:event_button_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCEspacoLocador(contexto, controlador, m).setVisible(true);
            }
        });
    }

    public void setEdit_diaria(String edit_diaria) {
        this.edit_diaria.setText(edit_diaria);
    }

    public void setEdit_endereco(String edit_endereco) {
        this.edit_endereco.setText(edit_endereco);
    }

    public void setEdit_lugares(String edit_lugares) {
        this.edit_lugares.setText(edit_lugares);
    }

    public void setEdit_lugares_ocupados(String ocupados) {
        this.edit_lugares_ocupados.setText(ocupados);
    }

    public void setEdit_tipo(String edit_tipo) {
        this.edit_tipo.setText(edit_tipo);
    }
    
    public void setIdEspaco(int id){
        this.idEspaco = id;
    }
    
    public void setTextComissao(String comissao){
        text_comissao.setText(comissao);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_editar;
    private javax.swing.JButton button_excluir;
    private javax.swing.JButton button_ok;
    private javax.swing.JTextField edit_diaria;
    private javax.swing.JTextField edit_endereco;
    private javax.swing.JTextField edit_lugares;
    private javax.swing.JTextField edit_lugares_ocupados;
    private javax.swing.JTextField edit_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text_comissao;
    private javax.swing.JLabel text_diaria;
    private javax.swing.JLabel text_endereco;
    private javax.swing.JLabel text_lugares;
    private javax.swing.JLabel text_status_e;
    private javax.swing.JLabel text_tipo;
    // End of variables declaration//GEN-END:variables
}
