/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador_view;

import javax.swing.JLabel;
import modelo.Cadastrar;

/**
 *
 * @author Joel
 */
public class VCadastrar extends VC {
    private static Cadastrar mCadastrar;
    private static ControladorMain contexto;
    /**
     * Creates new form VCadastrar
     */
    public VCadastrar(Cadastrar mCadastrar, ControladorMain contexto) {
        this.mCadastrar = mCadastrar;
        this.contexto   = contexto;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edit_nome = new javax.swing.JTextField();
        edit_email = new javax.swing.JTextField();
        edit_senha = new javax.swing.JPasswordField();
        radio_locador = new javax.swing.JRadioButton();
        radio_locatario = new javax.swing.JRadioButton();
        button_cadastrar = new javax.swing.JButton();
        text_msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastrar Conta");

        jLabel2.setText("Nome");

        jLabel3.setText("Email");

        jLabel4.setText("Senha");

        jLabel5.setText("Você é um");

        edit_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_nomeActionPerformed(evt);
            }
        });

        buttonGroup4.add(radio_locador);
        radio_locador.setText("Locador");

        buttonGroup4.add(radio_locatario);
        radio_locatario.setText("Locatário (Cliente apenas)");

        button_cadastrar.setText("Cadastrar");
        button_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cadastrarActionPerformed(evt);
            }
        });

        text_msg.setText("Preencha os campos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(edit_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(edit_email)
                                .addComponent(edit_senha)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radio_locador)
                                    .addGap(18, 18, 18)
                                    .addComponent(radio_locatario)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text_msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(text_msg, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edit_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(edit_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(edit_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radio_locador)
                    .addComponent(radio_locatario))
                .addGap(18, 18, 18)
                .addComponent(button_cadastrar)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_nomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_edit_nomeActionPerformed

    private void button_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cadastrarActionPerformed
        // TODO add your handling code here:
        mCadastrar.setSemail(edit_email.getText());
        mCadastrar.setSnome(edit_nome.getText());
        mCadastrar.setSsenha(edit_senha.getText());
        
        String usuario = "";
        
        if(radio_locador.isSelected())
            usuario = "Locador";
        else
            usuario = "Locatario";
        
        mCadastrar.setSusuario(usuario);
        mCadastrar.cadastrar();
        contexto.carregando(this, "Preste a atenção nos campo!");
    }//GEN-LAST:event_button_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCadastrar(mCadastrar, contexto).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton button_cadastrar;
    private javax.swing.JTextField edit_email;
    private javax.swing.JTextField edit_nome;
    private javax.swing.JPasswordField edit_senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radio_locador;
    private javax.swing.JRadioButton radio_locatario;
    private javax.swing.JLabel text_msg;
    // End of variables declaration//GEN-END:variables
    public JLabel getText_msg() {
        return text_msg;
    }
    
    @Override
    public void setMensagem(String msg){
        text_msg.setText(msg);
    }
}
